include:
  remote: 'https://gitlab.com/mts-teta-public/devops-tools/-/raw/master/.gitlab-ci-main.yml'
build image:
  variables:
    DB_LOGIN: $DB_LOGIN
    DB_PASSWORD: $DB_PASSWORD

newman tests:
  variables:
    TEST_COLLECTION_NAME: auth
    SERVICE_API_ENDPOINT: auth:3000
