include:
  remote: 'https://gitlab.com/mts-teta-public/devops-tools/-/raw/master/.gitlab-ci-main.yml'
build image:
  variables:
    DB_LOGIN: $DB_LOGIN
    DB_PASSWORD: $DB_PASSWORD

deploy:
  variables:
    HELM_TEMPLATE: https://gitlab.com/g6834/team41/auth/-/raw/development/infrastructure/auth.tgz

newman tests:
  variables:
    TEST_COLLECTION_NAME: auth
    SERVICE_API_ENDPOINT: auth:3000
