host_address: :3000
metrics_address: :9000
sentry_dsn: https://b38d5b4e3d27449cba4a66f4b2eac9e1@sentry.k8s.golang-mts-teta.ru/12
jaeger_collector: http://jaeger-instance-collector.observability:14268/api/traces